### ISSUE TITLE
Notebooks are not up to date with duckietown world version

### ISSUE THREAD

**Issue by AmaurX** [duckietown/duckietown-world#16]
@AndreaCensi 

We are trying to just visualize the result of the changed maps, but using the notebooks with the 1.0.23 version of the duckietown world does not work anymore : when calling 
`m = dw.construct_map(map_data, tile_size=0.61)` we get that the argument tile_size is undefined, but when we remove it it seems like the code needs it anyway...

Do you have a fix?

**Comment by AndreaCensi** [comment]
@AmaurX do not pass the tile_size parameter.

But do put the tile_size as a field in the map. (as in the yaml file)
