### ISSUE TITLE
There is a typo in `groundtags` layer.

### ISSUE THREAD

**Issue by afdaniele** [duckietown/duckietown-world#63]
Objects in the `groundtags` layer are called `grountag_XYZ`, missing a `d`.

![image](https://user-images.githubusercontent.com/22665009/126234061-05e9b558-9cfe-4004-9031-4060cc1d3f4f.png)

**Comment by light5551** [comment]
https://github.com/OSLL/dt-gui-tools/commit/ba68861f5a03a3b6828318bb55254dbae1456fa0
